#!/bin/sh
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.0 --con ../../WebServer/data/Medline/medline_sents_parsed.con.0 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.0 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.0 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS0
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.1 --con ../../WebServer/data/Medline/medline_sents_parsed.con.1 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.1 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.1 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS1
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.2 --con ../../WebServer/data/Medline/medline_sents_parsed.con.2 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.2 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.2 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS2
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.3 --con ../../WebServer/data/Medline/medline_sents_parsed.con.3 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.3 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.3 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS3
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.4 --con ../../WebServer/data/Medline/medline_sents_parsed.con.4 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.4 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.4 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS4
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.5 --con ../../WebServer/data/Medline/medline_sents_parsed.con.5 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.5 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.5 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS5
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.6 --con ../../WebServer/data/Medline/medline_sents_parsed.con.6 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.6 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.6 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS6
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.7 --con ../../WebServer/data/Medline/medline_sents_parsed.con.7 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.7 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.7 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS7
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.8 --con ../../WebServer/data/Medline/medline_sents_parsed.con.8 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.8 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.8 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS8
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.9 --con ../../WebServer/data/Medline/medline_sents_parsed.con.9 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.9 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.9 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS9
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.10 --con ../../WebServer/data/Medline/medline_sents_parsed.con.10 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.10 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.10 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS10
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.11 --con ../../WebServer/data/Medline/medline_sents_parsed.con.11 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.11 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.11 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS11
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.12 --con ../../WebServer/data/Medline/medline_sents_parsed.con.12 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.12 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.12 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS12
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.13 --con ../../WebServer/data/Medline/medline_sents_parsed.con.13 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.13 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.13 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS13
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.14 --con ../../WebServer/data/Medline/medline_sents_parsed.con.14 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.14 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.14 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS14
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.15 --con ../../WebServer/data/Medline/medline_sents_parsed.con.15 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.15 -c CCS --output ../../WebServer/data/Medline/medline_CCS_classifications.txt.15 -p ../../WebServer/src/nltk_maxent_CCS.pkl 2> tempCCS15

./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.0 --con ../../WebServer/data/Medline/medline_sents_parsed.con.0 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.0 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.0 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT0
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.1 --con ../../WebServer/data/Medline/medline_sents_parsed.con.1 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.1 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.1 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT1
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.2 --con ../../WebServer/data/Medline/medline_sents_parsed.con.2 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.2 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.2 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT2
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.3 --con ../../WebServer/data/Medline/medline_sents_parsed.con.3 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.3 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.3 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT3
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.4 --con ../../WebServer/data/Medline/medline_sents_parsed.con.4 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.4 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.4 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT4
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.5 --con ../../WebServer/data/Medline/medline_sents_parsed.con.5 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.5 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.5 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT5
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.6 --con ../../WebServer/data/Medline/medline_sents_parsed.con.6 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.6 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.6 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT6
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.7 --con ../../WebServer/data/Medline/medline_sents_parsed.con.7 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.7 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.7 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT7
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.8 --con ../../WebServer/data/Medline/medline_sents_parsed.con.8 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.8 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.8 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT8
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.9 --con ../../WebServer/data/Medline/medline_sents_parsed.con.9 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.9 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.9 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT9
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.10 --con ../../WebServer/data/Medline/medline_sents_parsed.con.10 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.10 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.10 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT10
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.11 --con ../../WebServer/data/Medline/medline_sents_parsed.con.11 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.11 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.11 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT11
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.12 --con ../../WebServer/data/Medline/medline_sents_parsed.con.12 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.12 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.12 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT12
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.13 --con ../../WebServer/data/Medline/medline_sents_parsed.con.13 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.13 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.13 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT13
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.14 --con ../../WebServer/data/Medline/medline_sents_parsed.con.14 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.14 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.14 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT14
./Experiment.py --classify --txt ../../WebServer/data/Medline/medline_annotation_units.txt.adjusted.15 --con ../../WebServer/data/Medline/medline_sents_parsed.con.15 --dep ../../WebServer/data/Medline/medline_sents_parsed.dep.15 -c PT --output ../../WebServer/data/Medline/medline_PT_classifications.txt.15 -p ../../WebServer/src/nltk_maxent_PT.pkl 2> tempPT15




